### ISSUE TITLE
qt, zlib, expat no longer available at URLs

### ISSUE THREAD

**Issue by jmduarte** [cms-outreach/ispy#3]
https://github.com/cms-outreach/ispy/blob/linux64/externals/CMakeLists.txt#L26
https://github.com/cms-outreach/ispy/blob/linux64/externals/CMakeLists.txt#L73
https://github.com/cms-outreach/ispy/blob/linux64/externals/CMakeLists.txt#L52

zlib URL needs to be updated to, e.g.

                    URL http://zlib.net/zlib-1.2.11.tar.gz 

and qt URL needs to be updated to, e.g.

                    URL https://download.qt.io/archive/qt/4.8/4.8.5/qt-everywhere-opensource-src-4.8.5.tar.gz

and expat URL,

                    URL http://downloads.sourceforge.net/expat/expat-2.0.1.tar.gz

**Comment by tpmccauley** [comment]
The desktop application is no longer supported. Development has moved to the browser-based iSpy WebGL: https://github.com/cms-outreach/ispy-webgl
